### ISSUE TITLE
_data/irc_versions.yml should refer to drafts as drafts

### ISSUE THREAD

**Issue by Zarthus** [ircv3/ircv3.github.io#131]
(if you ask me, at least!)

Make the following YML:

```yaml
v3.3:
  name: IRCv3.3 Draft
  note: >
    **These specifications are drafts and are NOT completed IRCv3 specs.**

    These caps are generally implemented with the `draft/` prefix until they are made into released IRCv3 specifications.
  specs:
    message-tags:
```

in either:
```yaml
draft/v3.3:  # <--
  name: IRCv3.3 Draft
  note: >
    **These specifications are drafts and are NOT completed IRCv3 specs.**

    These caps are generally implemented with the `draft/` prefix until they are made into released IRCv3 specifications.
  specs:
    message-tags:
```

or
```yaml
v3.3:
  name: IRCv3.3 Draft
  note: >
    **These specifications are drafts and are NOT completed IRCv3 specs.**

    These caps are generally implemented with the `draft/` prefix until they are made into released IRCv3 specifications.
  specs:
    draft/message-tags:  # <--
```

This change stops accidentally advertising a draft as a finished product.
